export const quiz = {
  Mathematics: [
    {
      id: 1,
      question: `What is the value of x if 2x + 6 = 14?`,
      options: { a: `3`, b: `4`, c: `5`, d: `6` },
      answer: `b`,
      answerText: `x = 4`,
    },
    {
      id: 2,
      question: `Simplify: 3/4 + 2/3`,
      options: { a: `17/12`, b: `12/17`, c: `13/12`, d: `19/12` },
      answer: `d`,
      answerText: `19/12`,
    },
    {
      id: 3,
      question: `Find the area of a triangle with base 10 cm and height 8 cm`,
      options: { a: `40 cm²`, b: `80 cm²`, c: `50 cm²`, d: `60 cm²` },
      answer: `a`,
      answerText: `40 cm²`,
    },
    {
      id: 4,
      question: `The mean of 2, 4, 6, 8, 10 is:`,
      options: { a: `5`, b: `6`, c: `7`, d: `8` },
      answer: `b`,
      answerText: `6`,
    },
    {
      id: 5,
      question: `Solve: √144`,
      options: { a: `10`, b: `11`, c: `12`, d: `14` },
      answer: `c`,
      answerText: `12`,
    },
    {
      id: 6,
      question: `If y = 2x and x = 5, what is y?`,
      options: { a: `10`, b: `5`, c: `15`, d: `20` },
      answer: `a`,
      answerText: `10`,
    },
    {
      id: 7,
      question: `Convert 0.75 to a fraction`,
      options: { a: `3/4`, b: `2/5`, c: `7/10`, d: `4/5` },
      answer: `a`,
      answerText: `3/4`,
    },
    {
      id: 8,
      question: `What is the perimeter of a square of side 7 cm?`,
      options: { a: `14 cm`, b: `21 cm`, c: `28 cm`, d: `35 cm` },
      answer: `c`,
      answerText: `28 cm`,
    },
    {
      id: 9,
      question: `Find the LCM of 6 and 8`,
      options: { a: `12`, b: `24`, c: `18`, d: `36` },
      answer: `b`,
      answerText: `24`,
    },
    {
      id: 10,
      question: `What is 25% of 200?`,
      options: { a: `25`, b: `40`, c: `50`, d: `75` },
      answer: `c`,
      answerText: `50`,
    },
  ],

  EnglishLanguage: [
    {
      id: 1,
      question: `Choose the correct synonym of 'Happy'`,
      options: { a: `Sad`, b: `Joyful`, c: `Angry`, d: `Upset` },
      answer: `b`,
      answerText: `Joyful`,
    },
    {
      id: 2,
      question: `What is the antonym of 'Strong'?`,
      options: { a: `Weak`, b: `Brave`, c: `Tough`, d: `Bold` },
      answer: `a`,
      answerText: `Weak`,
    },
    {
      id: 3,
      question: `Which of the following is a noun?`,
      options: { a: `Run`, b: `Beautiful`, c: `Chair`, d: `Quickly` },
      answer: `c`,
      answerText: `Chair`,
    },
    {
      id: 4,
      question: `What is the plural of 'Child'?`,
      options: { a: `Childs`, b: `Children`, c: `Childes`, d: `Childer` },
      answer: `b`,
      answerText: `Children`,
    },
    {
      id: 5,
      question: `Fill in the blank: She ___ to school yesterday`,
      options: { a: `go`, b: `went`, c: `gone`, d: `going` },
      answer: `b`,
      answerText: `went`,
    },
    {
      id: 6,
      question: `Identify the adjective: The tall man walked quickly`,
      options: { a: `Tall`, b: `Man`, c: `Walked`, d: `Quickly` },
      answer: `a`,
      answerText: `Tall`,
    },
    {
      id: 7,
      question: `Which is a correct sentence?`,
      options: {
        a: `He are coming`,
        b: `She is here`,
        c: `They was late`,
        d: `I going home`,
      },
      answer: `b`,
      answerText: `She is here`,
    },
    {
      id: 8,
      question: `What figure of speech is: 'The sun smiled at us'`,
      options: { a: `Metaphor`, b: `Personification`, c: `Simile`, d: `Irony` },
      answer: `b`,
      answerText: `Personification`,
    },
    {
      id: 9,
      question: `Choose the correct spelling`,
      options: { a: `Recieve`, b: `Receive`, c: `Receeve`, d: `Receve` },
      answer: `b`,
      answerText: `Receive`,
    },
    {
      id: 10,
      question: `What is the past tense of 'Sing'?`,
      options: { a: `Sang`, b: `Singed`, c: `Sung`, d: `Sing` },
      answer: `a`,
      answerText: `Sang`,
    },
  ],

  Physics: [
    {
      id: 1,
      question: `What is the SI unit of Force?`,
      options: { a: `Newton`, b: `Joule`, c: `Watt`, d: `Pascal` },
      answer: `a`,
      answerText: `Newton`,
    },
    {
      id: 2,
      question: `Speed is defined as:`,
      options: {
        a: `Distance/Time`,
        b: `Time/Distance`,
        c: `Force/Area`,
        d: `Mass/Volume`,
      },
      answer: `a`,
      answerText: `Distance/Time`,
    },
    {
      id: 3,
      question: `The acceleration due to gravity on Earth is:`,
      options: { a: `8.9 m/s²`, b: `9.8 m/s²`, c: `10.8 m/s²`, d: `12 m/s²` },
      answer: `b`,
      answerText: `9.8 m/s²`,
    },
    {
      id: 4,
      question: `Which instrument measures current?`,
      options: {
        a: `Voltmeter`,
        b: `Thermometer`,
        c: `Ammeter`,
        d: `Barometer`,
      },
      answer: `c`,
      answerText: `Ammeter`,
    },
    {
      id: 5,
      question: `Which of these is a scalar quantity?`,
      options: { a: `Velocity`, b: `Acceleration`, c: `Force`, d: `Mass` },
      answer: `d`,
      answerText: `Mass`,
    },
    {
      id: 6,
      question: `The first law of motion is also called:`,
      options: {
        a: `Law of Inertia`,
        b: `Law of Gravity`,
        c: `Law of Energy`,
        d: `Law of Force`,
      },
      answer: `a`,
      answerText: `Law of Inertia`,
    },
    {
      id: 7,
      question: `What is the unit of Power?`,
      options: { a: `Joule`, b: `Watt`, c: `Newton`, d: `Pascal` },
      answer: `b`,
      answerText: `Watt`,
    },
    {
      id: 8,
      question: `Which energy is possessed by a body due to motion?`,
      options: {
        a: `Potential energy`,
        b: `Kinetic energy`,
        c: `Thermal energy`,
        d: `Nuclear energy`,
      },
      answer: `b`,
      answerText: `Kinetic energy`,
    },
    {
      id: 9,
      question: `Light travels fastest in:`,
      options: { a: `Water`, b: `Air`, c: `Vacuum`, d: `Glass` },
      answer: `c`,
      answerText: `Vacuum`,
    },
    {
      id: 10,
      question: `Which of these is not a renewable source of energy?`,
      options: { a: `Coal`, b: `Solar`, c: `Wind`, d: `Hydro` },
      answer: `a`,
      answerText: `Coal`,
    },
  ],

  Chemistry: [
    {
      id: 1,
      question: `What is the chemical symbol of Sodium?`,
      options: { a: `Na`, b: `So`, c: `S`, d: `Sn` },
      answer: `a`,
      answerText: `Na`,
    },
    {
      id: 2,
      question: `Which gas is used in respiration?`,
      options: {
        a: `Carbon dioxide`,
        b: `Oxygen`,
        c: `Nitrogen`,
        d: `Hydrogen`,
      },
      answer: `b`,
      answerText: `Oxygen`,
    },
    {
      id: 3,
      question: `pH less than 7 indicates:`,
      options: { a: `Neutral`, b: `Acidic`, c: `Basic`, d: `Salty` },
      answer: `b`,
      answerText: `Acidic`,
    },
    {
      id: 4,
      question: `Which element has atomic number 1?`,
      options: { a: `Oxygen`, b: `Hydrogen`, c: `Helium`, d: `Nitrogen` },
      answer: `b`,
      answerText: `Hydrogen`,
    },
    {
      id: 5,
      question: `H₂O is the chemical formula of:`,
      options: { a: `Hydrogen`, b: `Oxygen`, c: `Water`, d: `Carbon dioxide` },
      answer: `c`,
      answerText: `Water`,
    },
    {
      id: 6,
      question: `Which gas turns lime water milky?`,
      options: {
        a: `Carbon dioxide`,
        b: `Oxygen`,
        c: `Nitrogen`,
        d: `Hydrogen`,
      },
      answer: `a`,
      answerText: `Carbon dioxide`,
    },
    {
      id: 7,
      question: `The process of converting liquid to gas is:`,
      options: {
        a: `Condensation`,
        b: `Evaporation`,
        c: `Freezing`,
        d: `Melting`,
      },
      answer: `b`,
      answerText: `Evaporation`,
    },
    {
      id: 8,
      question: `The smallest particle of an element is:`,
      options: { a: `Atom`, b: `Molecule`, c: `Ion`, d: `Electron` },
      answer: `a`,
      answerText: `Atom`,
    },
    {
      id: 9,
      question: `Which of these is a noble gas?`,
      options: { a: `Helium`, b: `Oxygen`, c: `Nitrogen`, d: `Carbon` },
      answer: `a`,
      answerText: `Helium`,
    },
    {
      id: 10,
      question: `What is the chemical symbol for Iron?`,
      options: { a: `Ir`, b: `Fe`, c: `In`, d: `I` },
      answer: `b`,
      answerText: `Fe`,
    },
  ],

  FurtherMathematics: [
    {
      id: 1,
      question: `Differentiate y = x²`,
      options: { a: `2x`, b: `x`, c: `x²`, d: `2` },
      answer: `a`,
      answerText: `2x`,
    },
    {
      id: 2,
      question: `Integrate y = 2x`,
      options: { a: `x² + C`, b: `2x² + C`, c: `x + C`, d: `2 + C` },
      answer: `a`,
      answerText: `x² + C`,
    },
    {
      id: 3,
      question: `Find the determinant of [[1,2],[3,4]]`,
      options: { a: `-2`, b: `-5`, c: `2`, d: `5` },
      answer: `a`,
      answerText: `-2`,
    },
    {
      id: 4,
      question: `Solve: sin 30°`,
      options: { a: `1`, b: `0.5`, c: `√3/2`, d: `0` },
      answer: `b`,
      answerText: `0.5`,
    },
    {
      id: 5,
      question: `If log₁₀x = 2, then x = ?`,
      options: { a: `10`, b: `20`, c: `100`, d: `1000` },
      answer: `c`,
      answerText: `100`,
    },
    {
      id: 6,
      question: `Find the inverse of f(x) = 2x + 3`,
      options: { a: `(x-3)/2`, b: `(x+3)/2`, c: `2x-3`, d: `1/(2x+3)` },
      answer: `a`,
      answerText: `(x-3)/2`,
    },
    {
      id: 7,
      question: `Find the derivative of y = sinx`,
      options: { a: `cosx`, b: `-cosx`, c: `-sinx`, d: `tanx` },
      answer: `a`,
      answerText: `cosx`,
    },
    {
      id: 8,
      question: `Evaluate cos²x + sin²x`,
      options: { a: `0`, b: `1`, c: `2`, d: `x` },
      answer: `b`,
      answerText: `1`,
    },
    {
      id: 9,
      question: `Find the solution to x² - 9 = 0`,
      options: { a: `±3`, b: `±9`, c: `0`, d: `3` },
      answer: `a`,
      answerText: `±3`,
    },
    {
      id: 10,
      question: `If f(x) = x² and g(x) = x+1, find f(g(x))`,
      options: { a: `x²+1`, b: `(x+1)²`, c: `x²+x+1`, d: `x+1` },
      answer: `b`,
      answerText: `(x+1)²`,
    },
  ],

  Biology: [
    {
      id: 1,
      question: `The basic unit of life is:`,
      options: { a: `Tissue`, b: `Organ`, c: `Cell`, d: `Organism` },
      answer: `c`,
      answerText: `Cell`,
    },
    {
      id: 2,
      question: `Which organ pumps blood?`,
      options: { a: `Lungs`, b: `Heart`, c: `Brain`, d: `Liver` },
      answer: `b`,
      answerText: `Heart`,
    },
    {
      id: 3,
      question: `Plants produce food through:`,
      options: {
        a: `Respiration`,
        b: `Photosynthesis`,
        c: `Digestion`,
        d: `Fermentation`,
      },
      answer: `b`,
      answerText: `Photosynthesis`,
    },
    {
      id: 4,
      question: `Which blood cells fight diseases?`,
      options: {
        a: `Red blood cells`,
        b: `White blood cells`,
        c: `Platelets`,
        d: `Plasma`,
      },
      answer: `b`,
      answerText: `White blood cells`,
    },
    {
      id: 5,
      question: `The organ of sight is:`,
      options: { a: `Nose`, b: `Ear`, c: `Eye`, d: `Skin` },
      answer: `c`,
      answerText: `Eye`,
    },
    {
      id: 6,
      question: `Which part of the plant absorbs water?`,
      options: { a: `Stem`, b: `Leaf`, c: `Root`, d: `Flower` },
      answer: `c`,
      answerText: `Root`,
    },
    {
      id: 7,
      question: `The functional unit of the kidney is:`,
      options: { a: `Neuron`, b: `Nephron`, c: `Alveoli`, d: `Atrium` },
      answer: `b`,
      answerText: `Nephron`,
    },
    {
      id: 8,
      question: `What type of blood group is universal donor?`,
      options: { a: `A`, b: `B`, c: `O`, d: `AB` },
      answer: `c`,
      answerText: `O`,
    },
    {
      id: 9,
      question: `What is the green pigment in plants?`,
      options: {
        a: `Hemoglobin`,
        b: `Chlorophyll`,
        c: `Carotene`,
        d: `Xanthophyll`,
      },
      answer: `b`,
      answerText: `Chlorophyll`,
    },
    {
      id: 10,
      question: `Which organ controls body activities?`,
      options: { a: `Heart`, b: `Liver`, c: `Brain`, d: `Kidney` },
      answer: `c`,
      answerText: `Brain`,
    },
  ],

  ComputerScience: [
    {
      id: 1,
      question: `What does CPU stand for?`,
      options: {
        a: `Central Process Unit`,
        b: `Central Processing Unit`,
        c: `Computer Processing Unit`,
        d: `Control Processing Unit`,
      },
      answer: `b`,
      answerText: `Central Processing Unit`,
    },
    {
      id: 2,
      question: `Which device is an input device?`,
      options: { a: `Monitor`, b: `Printer`, c: `Keyboard`, d: `Speaker` },
      answer: `c`,
      answerText: `Keyboard`,
    },
    {
      id: 3,
      question: `The brain of the computer is:`,
      options: { a: `CPU`, b: `RAM`, c: `Hard disk`, d: `Monitor` },
      answer: `a`,
      answerText: `CPU`,
    },
    {
      id: 4,
      question: `Which is a storage device?`,
      options: { a: `Mouse`, b: `Keyboard`, c: `Hard disk`, d: `Printer` },
      answer: `c`,
      answerText: `Hard disk`,
    },
    {
      id: 5,
      question: `What does RAM stand for?`,
      options: {
        a: `Random Access Memory`,
        b: `Read And Memory`,
        c: `Ready Access Memory`,
        d: `Run Access Memory`,
      },
      answer: `a`,
      answerText: `Random Access Memory`,
    },
    {
      id: 6,
      question: `Which is an output device?`,
      options: { a: `Scanner`, b: `Mouse`, c: `Printer`, d: `Keyboard` },
      answer: `c`,
      answerText: `Printer`,
    },
    {
      id: 7,
      question: `Binary system is based on:`,
      options: { a: `10`, b: `100`, c: `2`, d: `8` },
      answer: `c`,
      answerText: `2`,
    },
    {
      id: 8,
      question: `The full meaning of URL is:`,
      options: {
        a: `Uniform Resource Locator`,
        b: `Universal Reference Link`,
        c: `Unified Research Locator`,
        d: `Uniform Referenced Link`,
      },
      answer: `a`,
      answerText: `Uniform Resource Locator`,
    },
    {
      id: 9,
      question: `Which key is used to delete characters backward?`,
      options: { a: `Delete`, b: `Backspace`, c: `Shift`, d: `Ctrl` },
      answer: `b`,
      answerText: `Backspace`,
    },
    {
      id: 10,
      question: `Which software controls the computer hardware?`,
      options: {
        a: `Application software`,
        b: `System software`,
        c: `Operating System`,
        d: `Utility software`,
      },
      answer: `c`,
      answerText: `Operating System`,
    },
  ],

  CivicEducation: [
    {
      id: 1,
      question: `Which is the supreme law of Nigeria?`,
      options: { a: `Constitution`, b: `Act`, c: `Bill`, d: `Decree` },
      answer: `a`,
      answerText: `Constitution`,
    },
    {
      id: 2,
      question: `Democracy means:`,
      options: {
        a: `Government by few`,
        b: `Government by all`,
        c: `Government by king`,
        d: `Government by soldiers`,
      },
      answer: `b`,
      answerText: `Government by all`,
    },
    {
      id: 3,
      question: `Who is the head of the judiciary in Nigeria?`,
      options: {
        a: `President`,
        b: `Chief Justice`,
        c: `Governor`,
        d: `Senate President`,
      },
      answer: `b`,
      answerText: `Chief Justice`,
    },
    {
      id: 4,
      question: `How many states are in Nigeria?`,
      options: { a: `30`, b: `35`, c: `36`, d: `37` },
      answer: `c`,
      answerText: `36`,
    },
    {
      id: 5,
      question: `Which color in the Nigerian flag stands for peace?`,
      options: { a: `Green`, b: `White`, c: `Black`, d: `Blue` },
      answer: `b`,
      answerText: `White`,
    },
    {
      id: 6,
      question: `The Nigerian coat of arms has how many horses?`,
      options: { a: `1`, b: `2`, c: `3`, d: `4` },
      answer: `b`,
      answerText: `2`,
    },
    {
      id: 7,
      question: `Citizenship can be acquired by:`,
      options: {
        a: `Birth`,
        b: `Registration`,
        c: `Naturalization`,
        d: `All of the above`,
      },
      answer: `d`,
      answerText: `All of the above`,
    },
    {
      id: 8,
      question: `Who makes laws in Nigeria?`,
      options: {
        a: `Judiciary`,
        b: `Legislature`,
        c: `Executive`,
        d: `Police`,
      },
      answer: `b`,
      answerText: `Legislature`,
    },
    {
      id: 9,
      question: `The symbol of justice is:`,
      options: { a: `Scales`, b: `Flag`, c: `Horse`, d: `Eagle` },
      answer: `a`,
      answerText: `Scales`,
    },
    {
      id: 10,
      question: `Which arm of government implements laws?`,
      options: {
        a: `Judiciary`,
        b: `Legislature`,
        c: `Executive`,
        d: `Traditional rulers`,
      },
      answer: `c`,
      answerText: `Executive`,
    },
  ],

  AgriculturalScience: [
    {
      id: 1,
      question: `Which is not a type of farming?`,
      options: {
        a: `Subsistence`,
        b: `Commercial`,
        c: `Nomadic`,
        d: `Industrial Revolution`,
      },
      answer: `d`,
      answerText: `Industrial Revolution`,
    },
    {
      id: 2,
      question: `Crop rotation helps to:`,
      options: {
        a: `Increase erosion`,
        b: `Conserve soil fertility`,
        c: `Waste land`,
        d: `Destroy crops`,
      },
      answer: `b`,
      answerText: `Conserve soil fertility`,
    },
    {
      id: 3,
      question: `Which is a cereal crop?`,
      options: { a: `Rice`, b: `Yam`, c: `Cassava`, d: `Cocoa` },
      answer: `a`,
      answerText: `Rice`,
    },
    {
      id: 4,
      question: `Which tool is used for weeding?`,
      options: { a: `Hoe`, b: `Axe`, c: `Cutlass`, d: `Hammer` },
      answer: `a`,
      answerText: `Hoe`,
    },
    {
      id: 5,
      question: `Animal droppings used as fertilizer are called:`,
      options: { a: `Compost`, b: `Manure`, c: `Mulch`, d: `Humus` },
      answer: `b`,
      answerText: `Manure`,
    },
    {
      id: 6,
      question: `Which of these is a legume?`,
      options: { a: `Beans`, b: `Maize`, c: `Rice`, d: `Wheat` },
      answer: `a`,
      answerText: `Beans`,
    },
    {
      id: 7,
      question: `The rearing of fish is called:`,
      options: {
        a: `Horticulture`,
        b: `Aquaculture`,
        c: `Apiculture`,
        d: `Poultry`,
      },
      answer: `b`,
      answerText: `Aquaculture`,
    },
    {
      id: 8,
      question: `The major nutrient from fertilizer is:`,
      options: { a: `Nitrogen`, b: `Oxygen`, c: `Carbon`, d: `Hydrogen` },
      answer: `a`,
      answerText: `Nitrogen`,
    },
    {
      id: 9,
      question: `The best method of land preparation is:`,
      options: {
        a: `Burning`,
        b: `Ploughing`,
        c: `Deforestation`,
        d: `Flooding`,
      },
      answer: `b`,
      answerText: `Ploughing`,
    },
    {
      id: 10,
      question: `Which is a tuber crop?`,
      options: { a: `Yam`, b: `Beans`, c: `Rice`, d: `Cocoa` },
      answer: `a`,
      answerText: `Yam`,
    },
  ],

  AnimalHusbandry: [
    {
      id: 1,
      question: `The young of a goat is called:`,
      options: { a: `Calf`, b: `Kid`, c: `Lamb`, d: `Cub` },
      answer: `b`,
      answerText: `Kid`,
    },
    {
      id: 2,
      question: `What is castration in animals?`,
      options: {
        a: `Feeding`,
        b: `Removal of testicles`,
        c: `Milking`,
        d: `Shearing`,
      },
      answer: `b`,
      answerText: `Removal of testicles`,
    },
    {
      id: 3,
      question: `Ruminant animals have how many stomach compartments?`,
      options: { a: `1`, b: `2`, c: `3`, d: `4` },
      answer: `d`,
      answerText: `4`,
    },
    {
      id: 4,
      question: `Which animal provides wool?`,
      options: { a: `Cow`, b: `Goat`, c: `Sheep`, d: `Pig` },
      answer: `c`,
      answerText: `Sheep`,
    },
    {
      id: 5,
      question: `What is the housing for poultry called?`,
      options: { a: `Barn`, b: `Pen`, c: `Coop`, d: `Sty` },
      answer: `c`,
      answerText: `Coop`,
    },
    {
      id: 6,
      question: `Which animal is a non-ruminant?`,
      options: { a: `Goat`, b: `Pig`, c: `Cow`, d: `Sheep` },
      answer: `b`,
      answerText: `Pig`,
    },
    {
      id: 7,
      question: `The male horse is called:`,
      options: { a: `Mare`, b: `Colt`, c: `Stallion`, d: `Foal` },
      answer: `c`,
      answerText: `Stallion`,
    },
    {
      id: 8,
      question: `Artificial insemination is:`,
      options: {
        a: `Natural mating`,
        b: `Manual feeding`,
        c: `Introduction of semen artificially`,
        d: `Vaccination`,
      },
      answer: `c`,
      answerText: `Introduction of semen artificially`,
    },
    {
      id: 9,
      question: `Which animal is reared mainly for milk?`,
      options: { a: `Hen`, b: `Cow`, c: `Goat`, d: `Sheep` },
      answer: `b`,
      answerText: `Cow`,
    },
    {
      id: 10,
      question: `What is the gestation period of a cow?`,
      options: { a: `3 months`, b: `6 months`, c: `9 months`, d: `12 months` },
      answer: `c`,
      answerText: `9 months`,
    },
  ],

  FoodAndNutrition: [
    {
      id: 1,
      question: `Proteins are mainly used for:`,
      options: { a: `Energy`, b: `Body building`, c: `Heat`, d: `Vitamins` },
      answer: `b`,
      answerText: `Body building`,
    },
    {
      id: 2,
      question: `Which vitamin is produced by sunlight?`,
      options: {
        a: `Vitamin A`,
        b: `Vitamin B`,
        c: `Vitamin C`,
        d: `Vitamin D`,
      },
      answer: `d`,
      answerText: `Vitamin D`,
    },
    {
      id: 3,
      question: `Deficiency of Vitamin C causes:`,
      options: { a: `Rickets`, b: `Scurvy`, c: `Goitre`, d: `Kwashiorkor` },
      answer: `b`,
      answerText: `Scurvy`,
    },
    {
      id: 4,
      question: `Carbohydrates are stored in the body as:`,
      options: { a: `Protein`, b: `Starch`, c: `Glycogen`, d: `Fat` },
      answer: `c`,
      answerText: `Glycogen`,
    },
    {
      id: 5,
      question: `Milk is a good source of:`,
      options: { a: `Iron`, b: `Calcium`, c: `Vitamin C`, d: `Iodine` },
      answer: `b`,
      answerText: `Calcium`,
    },
    {
      id: 6,
      question: `Which food group provides energy?`,
      options: {
        a: `Carbohydrates`,
        b: `Proteins`,
        c: `Vitamins`,
        d: `Minerals`,
      },
      answer: `a`,
      answerText: `Carbohydrates`,
    },
    {
      id: 7,
      question: `Kwashiorkor is caused by lack of:`,
      options: {
        a: `Carbohydrate`,
        b: `Protein`,
        c: `Vitamin A`,
        d: `Vitamin D`,
      },
      answer: `b`,
      answerText: `Protein`,
    },
    {
      id: 8,
      question: `Which nutrient repairs worn-out tissues?`,
      options: { a: `Fats`, b: `Carbohydrates`, c: `Proteins`, d: `Vitamins` },
      answer: `c`,
      answerText: `Proteins`,
    },
    {
      id: 9,
      question: `Iron deficiency leads to:`,
      options: { a: `Goitre`, b: `Anaemia`, c: `Rickets`, d: `Scurvy` },
      answer: `b`,
      answerText: `Anaemia`,
    },
    {
      id: 10,
      question: `Which mineral strengthens bones and teeth?`,
      options: { a: `Calcium`, b: `Iodine`, c: `Potassium`, d: `Sodium` },
      answer: `a`,
      answerText: `Calcium`,
    },
  ],

  Economics: [
    {
      id: 1,
      question: `Economics is the study of:`,
      options: {
        a: `Money only`,
        b: `Scarcity and choice`,
        c: `Wealth alone`,
        d: `Population`,
      },
      answer: `b`,
      answerText: `Scarcity and choice`,
    },
    {
      id: 2,
      question: `Which is a factor of production?`,
      options: { a: `Land`, b: `Money`, c: `Wealth`, d: `Loan` },
      answer: `a`,
      answerText: `Land`,
    },
    {
      id: 3,
      question: `The reward for labour is:`,
      options: { a: `Rent`, b: `Wages`, c: `Profit`, d: `Interest` },
      answer: `b`,
      answerText: `Wages`,
    },
    {
      id: 4,
      question: `Demand means:`,
      options: {
        a: `Desire for goods`,
        b: `Ability and willingness to buy`,
        c: `Wish for items`,
        d: `Price of goods`,
      },
      answer: `b`,
      answerText: `Ability and willingness to buy`,
    },
    {
      id: 5,
      question: `Which market structure has one seller?`,
      options: {
        a: `Monopoly`,
        b: `Perfect competition`,
        c: `Oligopoly`,
        d: `Monopsony`,
      },
      answer: `a`,
      answerText: `Monopoly`,
    },
    {
      id: 6,
      question: `GDP stands for:`,
      options: {
        a: `Gross Domestic Product`,
        b: `General Domestic Production`,
        c: `Gross Departmental Product`,
        d: `Government Development Plan`,
      },
      answer: `a`,
      answerText: `Gross Domestic Product`,
    },
    {
      id: 7,
      question: `Which curve slopes downward from left to right?`,
      options: { a: `Supply`, b: `Demand`, c: `Cost`, d: `Revenue` },
      answer: `b`,
      answerText: `Demand`,
    },
    {
      id: 8,
      question: `Opportunity cost is:`,
      options: {
        a: `Total cost`,
        b: `Next best alternative forgone`,
        c: `Fixed cost`,
        d: `Variable cost`,
      },
      answer: `b`,
      answerText: `Next best alternative forgone`,
    },
    {
      id: 9,
      question: `Which is a direct tax?`,
      options: {
        a: `Income tax`,
        b: `VAT`,
        c: `Excise duty`,
        d: `Custom duty`,
      },
      answer: `a`,
      answerText: `Income tax`,
    },
    {
      id: 10,
      question: `Inflation is a rise in:`,
      options: {
        a: `Employment`,
        b: `General price level`,
        c: `Production`,
        d: `Exports`,
      },
      answer: `b`,
      answerText: `General price level`,
    },
  ],
};
