// Session data mapping
export const sessionData = {
  "2018/2019": "JSS1",
  "2018/2020": "JSS2",
  "2019/2020": "JSS3",
  "2020/2021": "SS1",
  "2021/2022": "SS2",
  "2022/2023": "SS2",
  "2023/2024": "SS3",
};

// Term data mapping
export const termData = {
  "1st Term": "1st Term Results",
  "2nd Term": "2nd Term Results",
  "3rd Term": "3rd Term Results",
};

// Mock grade data for each session and term combination (total out of 100)
export const gradeData = {
  "2018/2019": {
    "1st Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Adeyemi",
        exam: 40,
        ca: 25,
        test: 15,
        total: 80,
        grade: "B",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Okoro",
        exam: 42,
        ca: 28,
        test: 16,
        total: 86,
        grade: "B",
      },
      {
        subject: "Basic Science",
        teacher: "Mr. Bello",
        exam: 38,
        ca: 27,
        test: 14,
        total: 79,
        grade: "C",
      },
      {
        subject: "Social Studies",
        teacher: "Ms. Nwosu",
        exam: 45,
        ca: 30,
        test: 17,
        total: 92,
        grade: "A",
      },
      {
        subject: "Home Economics",
        teacher: "Mrs. Adebayo",
        exam: 43,
        ca: 29,
        test: 16,
        total: 88,
        grade: "B",
      },
    ],
    "2nd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Adeyemi",
        exam: 44,
        ca: 28,
        test: 17,
        total: 89,
        grade: "B",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Okoro",
        exam: 46,
        ca: 30,
        test: 18,
        total: 94,
        grade: "A",
      },
      {
        subject: "Basic Science",
        teacher: "Mr. Bello",
        exam: 42,
        ca: 29,
        test: 16,
        total: 87,
        grade: "B",
      },
      {
        subject: "Social Studies",
        teacher: "Ms. Nwosu",
        exam: 48,
        ca: 32,
        test: 19,
        total: 99,
        grade: "A",
      },
      {
        subject: "Home Economics",
        teacher: "Mrs. Adebayo",
        exam: 47,
        ca: 31,
        test: 18,
        total: 96,
        grade: "A",
      },
    ],
    "3rd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Adeyemi",
        exam: 49,
        ca: 32,
        test: 19,
        total: 100,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Okoro",
        exam: 48,
        ca: 31,
        test: 18,
        total: 97,
        grade: "A",
      },
      {
        subject: "Basic Science",
        teacher: "Mr. Bello",
        exam: 45,
        ca: 30,
        test: 17,
        total: 92,
        grade: "A",
      },
      {
        subject: "Social Studies",
        teacher: "Ms. Nwosu",
        exam: 50,
        ca: 33,
        test: 20,
        total: 103,
        grade: "A",
      },
      {
        subject: "Home Economics",
        teacher: "Mrs. Adebayo",
        exam: 51,
        ca: 34,
        test: 20,
        total: 105,
        grade: "A",
      },
    ],
  },
  "2018/2020": {
    "1st Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Adeyemi",
        exam: 46,
        ca: 28,
        test: 17,
        total: 91,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Okoro",
        exam: 42,
        ca: 26,
        test: 15,
        total: 83,
        grade: "B",
      },
      {
        subject: "Basic Science",
        teacher: "Mr. Bello",
        exam: 48,
        ca: 30,
        test: 18,
        total: 96,
        grade: "A",
      },
      {
        subject: "Social Studies",
        teacher: "Ms. Nwosu",
        exam: 44,
        ca: 27,
        test: 16,
        total: 87,
        grade: "B",
      },
      {
        subject: "Home Economics",
        teacher: "Mrs. Adebayo",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "French",
        teacher: "Mr. Dubois",
        exam: 40,
        ca: 25,
        test: 14,
        total: 79,
        grade: "C",
      },
    ],
    "2nd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Adeyemi",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Okoro",
        exam: 46,
        ca: 28,
        test: 17,
        total: 91,
        grade: "A",
      },
      {
        subject: "Basic Science",
        teacher: "Mr. Bello",
        exam: 52,
        ca: 33,
        test: 20,
        total: 105,
        grade: "A",
      },
      {
        subject: "Social Studies",
        teacher: "Ms. Nwosu",
        exam: 48,
        ca: 30,
        test: 18,
        total: 96,
        grade: "A",
      },
      {
        subject: "Home Economics",
        teacher: "Mrs. Adebayo",
        exam: 54,
        ca: 34,
        test: 21,
        total: 109,
        grade: "A",
      },
      {
        subject: "French",
        teacher: "Mr. Dubois",
        exam: 44,
        ca: 27,
        test: 16,
        total: 87,
        grade: "B",
      },
    ],
    "3rd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Adeyemi",
        exam: 55,
        ca: 35,
        test: 21,
        total: 111,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Okoro",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "Basic Science",
        teacher: "Mr. Bello",
        exam: 53,
        ca: 34,
        test: 20,
        total: 107,
        grade: "A",
      },
      {
        subject: "Social Studies",
        teacher: "Ms. Nwosu",
        exam: 51,
        ca: 32,
        test: 19,
        total: 102,
        grade: "A",
      },
      {
        subject: "Home Economics",
        teacher: "Mrs. Adebayo",
        exam: 57,
        ca: 36,
        test: 22,
        total: 115,
        grade: "A",
      },
      {
        subject: "French",
        teacher: "Mr. Dubois",
        exam: 48,
        ca: 30,
        test: 18,
        total: 96,
        grade: "A",
      },
    ],
  },
  "2019/2020": {
    "1st Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Johnson",
        exam: 55,
        ca: 35,
        test: 21,
        total: 111,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Williams",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "Basic Technology",
        teacher: "Mr. Davis",
        exam: 53,
        ca: 34,
        test: 20,
        total: 107,
        grade: "A",
      },
      {
        subject: "Social Studies",
        teacher: "Dr. Thompson",
        exam: 48,
        ca: 30,
        test: 18,
        total: 96,
        grade: "A",
      },
      {
        subject: "Agricultural Science",
        teacher: "Ms. Roberts",
        exam: 57,
        ca: 36,
        test: 22,
        total: 115,
        grade: "A",
      },
    ],
    "2nd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Johnson",
        exam: 53,
        ca: 34,
        test: 20,
        total: 107,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Williams",
        exam: 47,
        ca: 30,
        test: 18,
        total: 95,
        grade: "A",
      },
      {
        subject: "Basic Technology",
        teacher: "Mr. Davis",
        exam: 51,
        ca: 32,
        test: 19,
        total: 102,
        grade: "A",
      },
      {
        subject: "Social Studies",
        teacher: "Dr. Thompson",
        exam: 52,
        ca: 33,
        test: 20,
        total: 105,
        grade: "A",
      },
      {
        subject: "Agricultural Science",
        teacher: "Ms. Roberts",
        exam: 55,
        ca: 35,
        test: 21,
        total: 111,
        grade: "A",
      },
    ],
    "3rd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Johnson",
        exam: 58,
        ca: 37,
        test: 22,
        total: 117,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Williams",
        exam: 52,
        ca: 33,
        test: 20,
        total: 105,
        grade: "A",
      },
      {
        subject: "Basic Technology",
        teacher: "Mr. Davis",
        exam: 54,
        ca: 35,
        test: 21,
        total: 110,
        grade: "A",
      },
      {
        subject: "Social Studies",
        teacher: "Dr. Thompson",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "Agricultural Science",
        teacher: "Ms. Roberts",
        exam: 59,
        ca: 38,
        test: 23,
        total: 120,
        grade: "A",
      },
    ],
  },
  "2020/2021": {
    "1st Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Anderson",
        exam: 46,
        ca: 28,
        test: 17,
        total: 91,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Ms. Parker",
        exam: 42,
        ca: 26,
        test: 15,
        total: 83,
        grade: "B",
      },
      {
        subject: "Physics",
        teacher: "Dr. Miller",
        exam: 48,
        ca: 30,
        test: 18,
        total: 96,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Mr. Wilson",
        exam: 44,
        ca: 27,
        test: 16,
        total: 87,
        grade: "B",
      },
      {
        subject: "Biology",
        teacher: "Mrs. Taylor",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mr. Clark",
        exam: 40,
        ca: 25,
        test: 14,
        total: 79,
        grade: "C",
      },
    ],
    "2nd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Anderson",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Ms. Parker",
        exam: 46,
        ca: 28,
        test: 17,
        total: 91,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Dr. Miller",
        exam: 52,
        ca: 33,
        test: 20,
        total: 105,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Mr. Wilson",
        exam: 48,
        ca: 30,
        test: 18,
        total: 96,
        grade: "A",
      },
      {
        subject: "Biology",
        teacher: "Mrs. Taylor",
        exam: 54,
        ca: 34,
        test: 21,
        total: 109,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mr. Clark",
        exam: 44,
        ca: 27,
        test: 16,
        total: 87,
        grade: "B",
      },
    ],
    "3rd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Anderson",
        exam: 55,
        ca: 35,
        test: 21,
        total: 111,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Ms. Parker",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Dr. Miller",
        exam: 53,
        ca: 34,
        test: 20,
        total: 107,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Mr. Wilson",
        exam: 51,
        ca: 32,
        test: 19,
        total: 102,
        grade: "A",
      },
      {
        subject: "Biology",
        teacher: "Mrs. Taylor",
        exam: 57,
        ca: 36,
        test: 22,
        total: 115,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mr. Clark",
        exam: 48,
        ca: 30,
        test: 18,
        total: 96,
        grade: "A",
      },
    ],
  },
  "2021/2022": {
    "1st Term": [
      {
        subject: "Mathematics",
        teacher: "Dr. Brown",
        exam: 57,
        ca: 36,
        test: 22,
        total: 115,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Garcia",
        exam: 53,
        ca: 34,
        test: 20,
        total: 107,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Mr. Martinez",
        exam: 55,
        ca: 35,
        test: 21,
        total: 111,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Ms. Lee",
        exam: 52,
        ca: 33,
        test: 20,
        total: 105,
        grade: "A",
      },
      {
        subject: "Biology",
        teacher: "Mr. Walker",
        exam: 59,
        ca: 38,
        test: 23,
        total: 120,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mrs. Hall",
        exam: 48,
        ca: 30,
        test: 18,
        total: 96,
        grade: "A",
      },
      {
        subject: "History",
        teacher: "Mr. Allen",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
    ],
    "2nd Term": [
      {
        subject: "Mathematics",
        teacher: "Dr. Brown",
        exam: 59,
        ca: 38,
        test: 23,
        total: 120,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Garcia",
        exam: 55,
        ca: 35,
        test: 21,
        total: 111,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Mr. Martinez",
        exam: 57,
        ca: 36,
        test: 22,
        total: 115,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Ms. Lee",
        exam: 54,
        ca: 34,
        test: 21,
        total: 109,
        grade: "A",
      },
      {
        subject: "Biology",
        teacher: "Mr. Walker",
        exam: 61,
        ca: 39,
        test: 24,
        total: 124,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mrs. Hall",
        exam: 52,
        ca: 33,
        test: 20,
        total: 105,
        grade: "A",
      },
      {
        subject: "History",
        teacher: "Mr. Allen",
        exam: 53,
        ca: 34,
        test: 20,
        total: 107,
        grade: "A",
      },
    ],
    "3rd Term": [
      {
        subject: "Mathematics",
        teacher: "Dr. Brown",
        exam: 61,
        ca: 39,
        test: 24,
        total: 124,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Garcia",
        exam: 57,
        ca: 36,
        test: 22,
        total: 115,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Mr. Martinez",
        exam: 59,
        ca: 38,
        test: 23,
        total: 120,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Ms. Lee",
        exam: 56,
        ca: 35,
        test: 22,
        total: 113,
        grade: "A",
      },
      {
        subject: "Biology",
        teacher: "Mr. Walker",
        exam: 63,
        ca: 40,
        test: 25,
        total: 128,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mrs. Hall",
        exam: 55,
        ca: 35,
        test: 21,
        total: 111,
        grade: "A",
      },
      {
        subject: "History",
        teacher: "Mr. Allen",
        exam: 56,
        ca: 35,
        test: 21,
        total: 112,
        grade: "A",
      },
    ],
  },
  "2022/2023": {
    "1st Term": [
      {
        subject: "Mathematics",
        teacher: "Prof. Scott",
        exam: 40,
        ca: 25,
        test: 14,
        total: 79,
        grade: "C",
      },
      {
        subject: "English Language",
        teacher: "Dr. Adams",
        exam: 44,
        ca: 27,
        test: 16,
        total: 87,
        grade: "B",
      },
      {
        subject: "Physics",
        teacher: "Mr. King",
        exam: 42,
        ca: 26,
        test: 15,
        total: 83,
        grade: "B",
      },
      {
        subject: "Chemistry",
        teacher: "Mrs. Wright",
        exam: 38,
        ca: 24,
        test: 13,
        total: 75,
        grade: "C",
      },
      {
        subject: "Biology",
        teacher: "Ms. Lopez",
        exam: 46,
        ca: 28,
        test: 17,
        total: 91,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mr. Hill",
        exam: 35,
        ca: 22,
        test: 12,
        total: 69,
        grade: "D",
      },
    ],
    "2nd Term": [
      {
        subject: "Mathematics",
        teacher: "Prof. Scott",
        exam: 44,
        ca: 27,
        test: 16,
        total: 87,
        grade: "B",
      },
      {
        subject: "English Language",
        teacher: "Dr. Adams",
        exam: 48,
        ca: 30,
        test: 18,
        total: 96,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Mr. King",
        exam: 46,
        ca: 28,
        test: 17,
        total: 91,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Mrs. Wright",
        exam: 41,
        ca: 26,
        test: 15,
        total: 82,
        grade: "B",
      },
      {
        subject: "Biology",
        teacher: "Ms. Lopez",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mr. Hill",
        exam: 40,
        ca: 25,
        test: 14,
        total: 79,
        grade: "C",
      },
    ],
    "3rd Term": [
      {
        subject: "Mathematics",
        teacher: "Prof. Scott",
        exam: 50,
        ca: 32,
        test: 19,
        total: 101,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Dr. Adams",
        exam: 52,
        ca: 33,
        test: 20,
        total: 105,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Mr. King",
        exam: 47,
        ca: 30,
        test: 18,
        total: 95,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Mrs. Wright",
        exam: 46,
        ca: 28,
        test: 17,
        total: 91,
        grade: "A",
      },
      {
        subject: "Biology",
        teacher: "Ms. Lopez",
        exam: 54,
        ca: 34,
        test: 21,
        total: 109,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mr. Hill",
        exam: 44,
        ca: 27,
        test: 16,
        total: 87,
        grade: "B",
      },
    ],
  },
  "2023/2024": {
    "1st Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Green",
        exam: 59,
        ca: 38,
        test: 23,
        total: 120,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Baker",
        exam: 57,
        ca: 36,
        test: 22,
        total: 115,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Dr. Nelson",
        exam: 59,
        ca: 38,
        test: 23,
        total: 120,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Ms. Carter",
        exam: 55,
        ca: 35,
        test: 21,
        total: 111,
        grade: "A",
      },
      {
        subject: "Biology",
        teacher: "Mr. Mitchell",
        exam: 61,
        ca: 39,
        test: 24,
        total: 124,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mrs. Perez",
        exam: 53,
        ca: 34,
        test: 20,
        total: 107,
        grade: "A",
      },
      {
        subject: "History",
        teacher: "Mr. Roberts",
        exam: 56,
        ca: 35,
        test: 22,
        total: 113,
        grade: "A",
      },
      {
        subject: "Economics",
        teacher: "Dr. Turner",
        exam: 58,
        ca: 37,
        test: 22,
        total: 117,
        grade: "A",
      },
    ],
    "2nd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Green",
        exam: 61,
        ca: 39,
        test: 24,
        total: 124,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Baker",
        exam: 59,
        ca: 38,
        test: 23,
        total: 120,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Dr. Nelson",
        exam: 59,
        ca: 38,
        test: 23,
        total: 120,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Ms. Carter",
        exam: 57,
        ca: 36,
        test: 22,
        total: 115,
        grade: "A",
      },
      {
        subject: "Biology",
        teacher: "Mr. Mitchell",
        exam: 63,
        ca: 40,
        test: 25,
        total: 128,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mrs. Perez",
        exam: 55,
        ca: 35,
        test: 21,
        total: 111,
        grade: "A",
      },
      {
        subject: "History",
        teacher: "Mr. Roberts",
        exam: 58,
        ca: 37,
        test: 22,
        total: 117,
        grade: "A",
      },
      {
        subject: "Economics",
        teacher: "Dr. Turner",
        exam: 60,
        ca: 38,
        test: 23,
        total: 121,
        grade: "A",
      },
    ],
    "3rd Term": [
      {
        subject: "Mathematics",
        teacher: "Mr. Green",
        exam: 63,
        ca: 40,
        test: 25,
        total: 128,
        grade: "A",
      },
      {
        subject: "English Language",
        teacher: "Mrs. Baker",
        exam: 61,
        ca: 39,
        test: 24,
        total: 124,
        grade: "A",
      },
      {
        subject: "Physics",
        teacher: "Dr. Nelson",
        exam: 61,
        ca: 39,
        test: 24,
        total: 124,
        grade: "A",
      },
      {
        subject: "Chemistry",
        teacher: "Ms. Carter",
        exam: 59,
        ca: 38,
        test: 23,
        total: 120,
        grade: "A",
      },
      {
        subject: "Biology",
        teacher: "Mr. Mitchell",
        exam: 65,
        ca: 41,
        test: 26,
        total: 132,
        grade: "A",
      },
      {
        subject: "Geography",
        teacher: "Mrs. Perez",
        exam: 57,
        ca: 36,
        test: 22,
        total: 115,
        grade: "A",
      },
      {
        subject: "History",
        teacher: "Mr. Roberts",
        exam: 60,
        ca: 38,
        test: 23,
        total: 121,
        grade: "A",
      },
      {
        subject: "Economics",
        teacher: "Dr. Turner",
        exam: 62,
        ca: 39,
        test: 24,
        total: 125,
        grade: "A",
      },
    ],
  },
};
